api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('todos/', views.TodoList.as_view()),
    path('todos/', views.TodoListCreate.as_view()),
    path('todos/<int:pk>', views.TodoRetrieveUpdateDestroy.as_view()),
    path('todos/<int:pk>/complete', views.TodoToggleComplete.as_view()),    
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('index1/', views.index1, name='index1'),
    # Add other paths here
    path("index2/", views.index2, name="index2"),
    path("sections/<int:num>", views.section, name="section"),
    path("index3/", views.index3, name="index3"),
    path("posts", views.posts, name="posts"),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tools/', include('core.urls')),
    path('api/', include('api.urls')),
    path('', include('learning_logs.urls')),
    
]

core/models.py
from django.db import models

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=300, blank=True, null=True)
    cover_image = models.ImageField(upload_to='cover_images/', blank=True, null=True)
    key_points = models.JSONField(blank=True, null=True)
    body = models.TextField()

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render
from .models import BlogPost
from django.http import Http404, HttpResponse
import time

from django.http import JsonResponse


# Create your views here.
def index1(request):
    post = BlogPost.objects.first()
    return render(request, 'core/index1.html', {"post": post})



# Create your views here.
def index2(request):
    return render(request, "core/index2.html")

# The texts are much longer in reality, but have
# been shortened here to save space
texts = ["Text 1", "Text 2", "Text 3"]

def section(request, num):
    if 1 <= num <= 3:
        return HttpResponse(texts[num - 1])
    else:
        raise Http404("No such section")
    



# Create your views here.
def index3(request):
    return render(request, "core/index3.html")

def posts(request):

    # Get start and end points
    start = int(request.GET.get("start") or 0)
    end = int(request.GET.get("end") or (start + 9))

    # Generate list of posts
    data = []
    for i in range(start, end + 1):
        data.append(f"Post #{i}")

    # Artificially delay speed of response
    time.sleep(1)

    # Return list of posts
    return JsonResponse({
        "posts": data
    })

core/templates/core/index2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Single Page</title>
        <style>
        </style>
        <script>

            // When back arrow is clicked, show previous section
            window.onpopstate = function(event) {
                console.log(event.state.section);
                showSection(event.state.section);
            }


            function showSection(section) {
            const baseUrl = "{% url 'core:section' 1 %}".replace("1", "");
            console.log(baseUrl);
            console.log(`${baseUrl}${section}`);
            fetch(`${baseUrl}${section}`)
            .then(response => response.text())
            .then(text => {
                console.log(text);
                document.querySelector('#content').innerHTML = text;
            });
        }

            document.addEventListener('DOMContentLoaded', function() {
                document.querySelectorAll('button').forEach(button => {
                    button.onclick = function() {
                        const section = this.dataset.section;

                        // Add the current state to the history
                        history.pushState({section: section}, "", `section${section}`);
                        showSection(section);
                    };
                });
            });
        </script>
    </head>
    <body>
        <h1>Hello!</h1>
        <button data-section="1">Section 1</button>
        <button data-section="2">Section 2</button>
        <button data-section="3">Section 3</button>
        <div id="content">
        </div>
    </body>
</html>

core/templates/core/index3.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Webpagex1xx</title>
        <style>

            @keyframes hide {
                0% {
                    opacity: 1;
                    height: 100%;
                    line-height: 100%;
                    padding: 20px;
                    margin-bottom: 10px;
                }
                75% {
                    opacity: 0;
                    height: 100%;
                    line-height: 100%;
                    padding: 20px;
                    margin-bottom: 10px;
                }
                100% {
                    opacity: 0;
                    height: 0px;
                    line-height: 0px;
                    padding: 0px;
                    margin-bottom: 0px;
                }
            }

            .hide  {
                float: right;
            }

            .post {
                background-color: #77dd11;
                padding: 20px;
                margin-bottom: 10px;
                animation-name: hide;
                animation-duration: 2s;
                animation-fill-mode: forwards;
                animation-play-state: paused;
            }

            body {
                padding-bottom: 50px;
            }

        </style>
        <script>

            // Start with first post
            let counter = 1;

            // Load posts 20 at a time
            const quantity = 20;

            // When DOM loads, render the first 20 posts
            document.addEventListener('DOMContentLoaded', load);

            // If scrolled to bottom, load the next 20 posts
            window.onscroll = () => {
                if (window.innerHeight + window.scrollY >= document.body.offsetHeight) {
                    load();
                }
            };

            // If hide button is clicked, delete the post
            document.addEventListener('click', event => {
                const element = event.target;
                if (element.className === 'hide') {
                    element.parentElement.style.animationPlayState = 'running';
                    element.parentElement.addEventListener('animationend', () =>  {
                        element.parentElement.remove();
                    });
                }
            });

            // Load next set of posts
            function load() {

                // Set start and end post numbers, and update counter
                const start = counter;
                const end = start + quantity - 1;
                counter = end + 1;


                // Construct the base URL properly
                const baseUrl = "{% url 'core:posts' %}";
                console.log(baseUrl);
                // Ensure that the baseUrl is absolute
                // Get new posts and add posts
                fetch(`${baseUrl}?start=${start}&end=${end}`)
                .then(response => response.json())
                .then(data => {
                    data.posts.forEach(add_post);
                })
            };

            // Add a new post with given contents to DOM
            function add_post(contents) {

                // Create new post
                const post = document.createElement('div');
                post.className = 'post';
                post.innerHTML = `${contents} <button class="hide">Hide</button>`;

                // Add post to DOM
                document.querySelector('#posts').append(post);
            };
        </script>
    </head>
    <body>
        <div id="posts">
        </div>
    </body>
</html>